# Generated by Django 5.0.4 on 2024-07-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_rename_branch_userprofile_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="minor",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="branch",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
