# Generated by Django 5.0.4 on 2024-07-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_remove_userprofile_department_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="branch",
            new_name="department",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="minor",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
