# Generated by Django 5.0.4 on 2024-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_rename_branch_userprofile_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
