# Generated by Django 5.0.4 on 2024-07-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_college"),
    ]

    operations = [
        migrations.RenameField(
            model_name="college",
            old_name="college",
            new_name="college_name",
        ),
    ]
