# Generated by Django 5.0.4 on 2024-07-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_rename_college_college_college_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="college",
            old_name="college_name",
            new_name="college",
        ),
    ]
